export const USER_APP_SHOW_EDIT_USER_MODAL = 'USER_APP_SHOW_EDIT_USER_MODAL';
export const USER_APP_HIDE_EDIT_USER_MODAL = 'USER_APP_HIDE_EDIT_USER_MODAL';
export const USER_APP_EDIT_USER = 'USER_APP_EDIT_USER';
