export const USER_APP_SHOW_EDIT_USER_MODAL = 'USER_APP_SHOW_EDIT_USER_MODAL';
export const USER_APP_HIDE_EDIT_USER_MODAL = 'USER_APP_HIDE_EDIT_USER_MODAL';
export const USER_APP_EDIT_USER_SUCCESS = 'USER_APP_EDIT_USER_SUCCESS';
export const USER_APP_EDIT_USER_STARTED = 'USER_APP_EDIT_USER_STARTED';
export const USER_APP_EDIT_USER_FAILURE = 'USER_APP_EDIT_USER_FAILURE';

export const USER_APP_GET_USER_STARTED = 'USER_APP_GET_USER_STARTED';
export const USER_APP_GET_USER_SUCCESS = 'USER_APP_GET_USER_SUCCESS';
export const USER_APP_GET_USER_FAILURE = 'USER_APP_GET_USER_FAILURE';

export const USER_APP_GET_USERS_STARTED = 'USER_APP_GET_USERS_STARTED';
export const USER_APP_GET_USERS_SUCCESS = 'USER_APP_GET_USERS_SUCCESS';
export const USER_APP_GET_USERS_FAILURE = 'USER_APP_GET_USERS_FAILURE';
