export const CHANNEL_LIST_CHANNEL_REMOVE_SUCCESS = 'CHANNEL_LIST_CHANNEL_REMOVE_SUCCESS';
export const CHANNEL_LIST_CHANNEL_CREATE = 'CHANNEL_LIST_CHANNEL_CREATE';
export const CHANNEL_LIST_CHANNEL_UPDATE_SUCCESS = 'CHANNEL_LIST_CHANNEL_UPDATE_SUCCESS';

export const CHANNEL_APP_SHOW_EDIT_CHANNEL = 'CHANNEL_APP_SHOW_EDIT_CHANNEL';
export const CHANNEL_APP_HIDE_EDIT_CHANNEL = 'CHANNEL_APP_HIDE_EDIT_CHANNEL';

export const CHANNEL_APP_SHOW_CREATE_CHANNEL = 'CHANNEL_APP_SHOW_CREATE_CHANNEL';
export const CHANNEL_APP_SELECT_CHANNEL = 'CHANNEL_APP_SELECT_CHANNEL';

export const CHANNEL_APP_LOADING_STARTED = 'CHANNEL_APP_LOADING_STARTED';
export const CHANNEL_APP_LOADING_SUCCESS = 'CHANNEL_APP_LOADING_SUCCESS';
export const CHANNEL_APP_LOADING_FAILURE = 'CHANNEL_APP_LOADING_FAILURE';

export const CHANNEL_APP_SET_VISIBILITY_FILTER = 'CHANNEL_APP_SET_VISIBILITY_FILTER';
export const CHANNEL_LIST_SHOW_LIST = 'CHANNEL_LIST_SHOW_LIST';
export const CHANNEL_LIST_HIDE_LIST = 'CHANNEL_LIST_HIDE_LIST';
