export const CHANNEL_LIST_CHANNEL_REMOVE = "CHANNEL_LIST_CHANNEL_REMOVE";
export const CHANNEL_LIST_CHANNEL_CREATE = "CHANNEL_LIST_CHANNEL_CREATE";
export const CHANNEL_LIST_CHANNEL_UPDATE = "CHANNEL_LIST_CHANNEL_UPDATE";

export const CHANNEL_APP_CHANNEL_UPDATE_CANCELLED = "CHANNEL_APP_CHANNEL_UPDATE_CANCELLED";
export const CHANNEL_APP_CHANNEL_UPDATE_STARTED = "CHANNEL_APP_CHANNEL_UPDATE_STARTED";

export const CHANNEL_APP_CHANNEL_EDITING_CANCELLED = "CHANNEL_APP_CHANNEL_EDITING_CANCELLED";
export const CHANNEL_APP_CHANNEL_EDITING_STARTED = "CHANNEL_APP_CHANNEL_EDITING_STARTED";
