export const CHANNEL_LIST_CHANNEL_REMOVE = "CHANNEL_LIST_CHANNEL_REMOVE";
export const CHANNEL_LIST_CHANNEL_CREATE = "CHANNEL_LIST_CHANNEL_CREATE";
export const CHANNEL_LIST_CHANNEL_UPDATE = "CHANNEL_LIST_CHANNEL_UPDATE";
