export const AUTHENTICATION_LOGIN_SUCCESS = 'AUTHENTICATION_LOGIN_SUCCESS';
export const AUTHENTICATION_LOGIN_STARTED = 'AUTHENTICATION_LOGIN_STARTED';
export const AUTHENTICATION_LOGIN_FAILURE = 'AUTHENTICATION_LOGIN_FAILURE';

export const AUTHENTICATION_REGISTER = 'AUTHENTICATION_REGISTER';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';
export const AUTHENTICATION_SWITCH_TO_REGISTRATION = 'AUTHENTICATION_SWITCH_TO_REGISTRATION';

export const AUTHENTICATION_SHOW_LOGIN_MODAL = 'AUTHENTICATION_SHOW_LOGIN_MODAL';
export const AUTHENTICATION_HIDE_LOGIN_MODAL = 'AUTHENTICATION_HIDE_LOGIN_MODAL';

export const AUTHENTICATION_SHOW_REGISTRATION_MODAL = 'AUTHENTICATION_SHOW_REGISTRATION_MODAL';
export const AUTHENTICATION_HIDE_REGISTRATION_MODAL = 'AUTHENTICATION_HIDE_REGISTRATION_MODAL';


